### ISSUE TITLE
Does not detect devices with Tasmota v7.1.2

### ISSUE THREAD

**Issue by drtorchwood** [KimNyholm/tasmota-device-locator#2]
After upgrading the tasmota version to v7.1.2 (previous version v6.7.1) the devices are not detected anymore (at least in the online version). 
Hint: The name of sonoff-tasmota changed to "tasmota" in v7.

**Comment by KimNyholm** [comment]
It has been decided that CORS is disabled in Tasmota. See 
[Local access security issue due to HTTP CORS header](https://github.com/arendst/Tasmota/issues/6767. Only devices, which have been configured to accept CORS from the server of Tasmota Device Locator or from any "*" will be found.
Configuration of CORS is implemented Tasmota in [Implement capability for setting CORS to a specific website instead of just enable for all websites](https://github.com/arendst/Tasmota/commit/6c3d02928617fa34291088df1d87ee2d75098e60#diff-fcd34ade37bfef5d1101e28526b364e6) and is the time of writing not yet released.
The Tasmota Device Locator will add documentation on its front page, to explain that CORS must be enabled on devices.

**Comment by KimNyholm** [comment]
Works as designed.
